/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Class.Account;
import Class.ClientSocket;
import Class.Message;
import Class.MessageType;
import com.github.sarxos.webcam.Webcam;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Trong Quynh
 */
public class VideoCall extends javax.swing.JFrame {

    /**
     * Creates new form VideoCall
     */
    private boolean stop = false;
    public VideoCall() throws IOException {
        initComponents();
    }
    private Account receiver;
    public VideoCall(Account receiver) throws IOException {
        initComponents();
        this.receiver = receiver;
        eventCallVideo();
    }
    
    private Account sender;
    private BufferedImage br;
    public VideoCall(Account sender, BufferedImage br) throws IOException {
        initComponents();
        this.sender = sender;
        this.br = br;
        eventReceiveVideoCall();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Screen = new javax.swing.JLabel();
        btn_Hangup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Screen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_Screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        btn_Hangup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hang-up.png"))); // NOI18N
        btn_Hangup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HangupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Hangup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 120, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HangupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HangupActionPerformed
        this.stop = true;
        dispose();
    }//GEN-LAST:event_btn_HangupActionPerformed

    private void eventCallVideo() throws IOException {
        System.out.println("Call video");
        ImageIcon ic;
        BufferedImage br;
        Webcam cam = Webcam.getDefault();
        cam.open();
        while (!stop) {            
            br = cam.getImage();
            ic = new ImageIcon(br);
            MessageType mtype = new MessageType(8, br);
            int currentAddressType = ClientSocket.getInstanceClientSocket().getCurrentAddressType();
            Message message = null;
            if(currentAddressType == 1){
                Account sender = ClientSocket.getInstanceClientSocket().getClient().getUserAccount();
                
                message = new Message(currentAddressType,sender,receiver, mtype);
            }
            ClientSocket.getInstanceClientSocket().getClient().reqMessage = message;
            ClientSocket.getInstanceClientSocket().getClient().runRequestThread();
            lbl_Screen.setIcon(ic);
        }
    }
    
    private void eventReceiveVideoCall(){
        ImageIcon ic;
        Webcam cam = Webcam.getDefault();
        cam.open();
        while (!stop) {            
            br = cam.getImage();
            ic = new ImageIcon(br);
            lbl_Screen.setIcon(ic);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoCall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VideoCall().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VideoCall.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Hangup;
    private javax.swing.JLabel lbl_Screen;
    // End of variables declaration//GEN-END:variables
}
